name: "Bug 反馈"
description: "在服务器内或外发现的错误或问题"
labels: [· Bug, 新反馈]
body:
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "检查项"
      description: "请逐个检查下列项目，并勾选确认。"
      options:
        - label: "我已在 [Issues 页面](https://github.com/coldsmilec/MOYU-Community/issues?q=is%3Aissue+)中搜索，确认了这一 Bug 未被提交过。"
          required: true
  - type: textarea
    id: "yml-2"
    attributes:
      label: 描述
      description: "详细描述该 Bug 的具体表现。"
    validations:
      required: true
  - type: textarea
    id: "yml-3"
    attributes:
      label: 重现步骤
      description: "详细描述要怎么操作才能再次触发这个 Bug。"
      value: |
        1、点击xxxx
        2、往下滚，然后点击xxxx
    validations:
      required: true
  - type: textarea
    id: "yml-4"
    attributes:
      label: 日志与附件(非必要)
      description: "上传启动器或minecraft错误报告（在崩溃时选择导出错误报告）"
      placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
    validations:
      required: false
